library(dplyr)
library(tidyr)

## Loading data
getwd()
# Set the directory containing your TSV files
file_directory <- "out/"

# List all TSV files generated by Kaiju in the directory
file_names <- list.files(file_directory, pattern = "\\.tsv$", full.names = TRUE)

# Function to read a single file
read_and_filter <- function(file) {
  data <- read.delim(file, sep = "\t")  # Read the TSV file
  return(data)
}

# Apply the function to all files and combine into a single data frame
filtered_combined_data <- bind_rows(lapply(file_names, read_and_filter))

## Table transformation to fit in phyloseq
# Add a sample column to the filtered data
filtered_combined_data <- filtered_combined_data %>%
  mutate(sample = basename(file))  # Extract the file name as the sample name

# Remove "_kaiju.out"
filtered_combined_data$sample <- gsub("_kaiju.out", "", filtered_combined_data$sample)

# Create the taxonomy table in wide format
taxonomy_table_wide <- filtered_combined_data %>%
  select(sample, taxon_name, reads) %>%  # Select relevant columns
  pivot_wider(
    names_from = taxon_name, 
    values_from = reads)

# Changing the table to generate the counts table and the taxonomy
head(taxonomy_table_wide)
otu_table <- taxonomy_table_wide[,2:2056]
row.names(otu_table) <- taxonomy_table_wide$sample
tax <- colnames(otu_table)
head(tax)
colnames(otu_table) = paste0("ASV", 1:ncol(otu_table))
asv <- colnames(otu_table)
head(asv)

# Generating tax table
asv_tax_map <- data.frame(
  ASV = asv,
  Taxon = tax,
  stringsAsFactors = FALSE
)

head(asv_tax_map)

# If your taxonomy strings are semicolon-separated (e.g., "k__Bacteria;p__Firmicutes;...")
# then we need to adjust them to the phyloseq format
tax_split <- strsplit(tax, ";")

# Convert to data frame
tax_table_phyloseq <- do.call(rbind, lapply(tax_split, function(x) trimws(x)))
colnames(tax_table_phyloseq) <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus")

# Add ASV IDs as rownames
rownames(tax_table_phyloseq) <- asv
head(tax_table_phyloseq)

# write the table to .csv
write.csv2(otu_table, file = "otu_table.csv")
write.csv2(tax_table_phyloseq, file = "tax_table.csv")
